@startuml
title Diagramme de cas d’utilisation -- Blog: Ouarzazate - Cinéma Atlas

actor "Touriste culturel" as Touriste
actor "Administrateur" as Admin
Éditeur <|--  Admin

rectangle "Blog Ouarzazate" {
  
  (Consulter la liste des articles) as UC1
  (Lire un article en détail) as UC2
  (Rechercher un article) as UC3
  (Sauvegarder un article) as UC4
  (Commenter sur un article) as UC7
  (Partager un article) as UC5
  (Gérer les articles) as UC6
}

Touriste -- UC1
Touriste -- UC2
Touriste -- UC3
Touriste -- UC4
Touriste -- UC5
Touriste -- UC7



Admin -- UC6

@enduml